config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get "items", to: "users#items"
  root to: "books#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  delete "/books/:id", to: "books#destroy"
  # get "books/:id", to: "books#show", as: "show_book"
  resources :books do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, except: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user, optional: true
  has_one_attached :cover
  has_many :rentals
  # validates :title, presence: true
  # validates :date_of_publication, presence: true
  # validates :author, presence: true
  validates_presence_of :title, :date_of_publication, :author, :daily_price, :address

  include PgSearch::Model
    pg_search_scope :book_search,
      against: [ :title, :author, :genre, :language ],
      associated_against: {
      user: [ :first_name, :last_name ]
      },
      using: {
      tsearch: { prefix: true }
      }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :rentals
  has_one_attached :photo_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, address_attributes: [:country, :postal_code]])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = policy_scope(Book).all
    @markers = @books.geocoded.map do |book|
      {
        lat: book.latitude,
        lng: book.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {book: book}),
        marker_html: render_to_string(partial: "marker", locals: {book: book})
      }
    end

    if params[:query].present?
      @books = Book.book_search(params[:query])
    else
      @books = Book.all
    end
  end

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    authorize @book

    if @book.save
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @book
  end

  def edit
    authorize @book
  end

  def update
    authorize @book

    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @book

    @book.destroy
    redirect_to root_path, status: :see_other, notice: "The book has been deleted!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :date_of_publication, :daily_price, :language, :description, :address, :cover)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  def index
    @rentals = policy_scope(Rental)
    @rentals = Rental.where(user_id: current_user.id)
  end

  def new
    @rental = Rental.new
    @book = Book.find(params[:book_id])
    authorize @rental
  end

  def show
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @book = Book.find(params[:book_id])
    @rental.book = @book

    authorize @rental

    if @rental.save!
      redirect_to rental_path(@rental)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @rental.destroy
    redirect_to root_path, status: :see_other, notice: "Your booking has been removed"
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized, only: [:items]
  def items() 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :genre %>
  <%= f.input :date_of_publication %>
  <%= f.input :daily_price %>
  <%= f.input :language %>
  <%= f.input :description %>
  <%= f.input :cover, as: :file %>
  <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/_info_window.html.erb
<h2><%= book.title %></h2>
<h3><%= book.author %></h3>
<p><%= book.address %></p>

app/views/books/_marker.html.erb
<div class="badge rounded-pill bg-primary fs-6">
  <%= book.title %>
</div>

app/views/books/edit.html.erb
<%= render "books/form" %>

app/views/books/index.html.erb
<div class="container">
</div>
<div class="banner">
  <h1>There are stories hidden on every bookshelf in the world.</h1>
  <p>Looking for a special book? Need some reading inspiration?</p>
  <p>Check out the books that are <b>close</b> to you, <b>connect</b> with fellow readers and <b>find</b> a book!</p>
  <p><%= link_to "Browse our books", new_book_path, class:"btn btn-primary btn-lg" %></p>
</div>
<div class="container">
</div>




<div class="content">
  <%# <div>
    <h1 class="logo-type">Book a Book</h1>
  </div> %>
  <% if user_signed_in? %>
      <p><%= link_to "Add a book", new_book_path, class:"btn btn-primary btn-lg" %></p>
      <p><%= link_to "Dashboard", rentals_path, class:"btn btn-primary btn-lg" %></p>
  <% end %>
        <h1 class="text-center" >There are stories hidden on every bookshelf in the world.</h1>
  <div class="card-product">
    <div class="container">
      <h4 class="text-center" >Looking for a special book? Need some reading inspiration?</h4>
      <h4 class="text-center" >Check out the books that are <b>close</b> to you, <b>connect</b> with fellow readers and <b>find</b> a book!</h4>
      <div class="cards">
        <div class="card">
          <% @books.each do |book| %>
          <h4 class="book-title"> Title: <%= book.title %></h4>
          <h5 class="book-author"> Author: <%= book.author %></h5>
          <h5 class="book-genre"> Genre: <%= book.genre %></h5>
          <h6 class="book-description"><em><%= book.description %></em></h6>
          <p><%= link_to "read more", book_path(book), class: "btn btn-info btn-sm "%></p>
          <p class="book-rental-price"><%= book.daily_price %>€</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/books/new.html.erb
<%= render "books/form" %>

app/views/books/show.html.erb
<h1>Title: <%= @book.title %></h1>
<h1>Author: <%= @book.author%></h1>
<h2><%= @book.description %></h2>
<h2>Language: <%= @book.language %></h2>
<h2>Daily price: <%= @book.daily_price%> Cents </h2>

<div>
  <%= link_to "Book this book", new_book_rental_path(@book)%>
  <%= link_to "Back to browsing", root_path, class: "btn btn-secondary"  %>

  <% if policy(@book).edit? %>
        <%= link_to "Edit", edit_book_path, class: "btn btn-warning" %>
  <% end %>
  <% if policy(@book).destroy? %>
        <%= link_to "Delete", book_path(@book), class: "btn btn-danger my-2", data: { turbo_method: :delete, turbo_confirm: "Do you want to delete the book?" } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookABook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my about page</h1>

app/views/pages/users_books.html.erb
<div class="container">
    <% current-user.books.each do |book| %>
      <div class="card">
        <%if book.cover.present?%>
          <%=  cl_image_tag(book.cover.key, :width => 250) %>
        <%else%>
          <%= cl_image_tag("v5hsn2kpxcxprmmx08o3nanwgb9w", :width => 250) %>
        <%end%>
        <h6 class="card-text book-description"><em><%= book.description %></em></h6>
        <p><%= link_to "read more", book_path(book), class: "btn btn-info btn-sm "%></p>
        <p class="card-text"><%= book.daily_price %>€ %></p>
        <p class="card-text"><%= book.description %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/rentals/index.html.erb
<h1>User can see all rentals</h1>

  <% if @rentals.empty? %>
  <strong><p>Your cart is currently empty</p></strong>
  <% else %>
  <ul>
    <% @rentals.each do |rental| %>
      <li><%= rental.book.title %></li>
      <li><%= rental.book.author %></li>
      <li>Date of Publication: <%= rental.book.date_of_publication%></li>
      <li>Start Date: <%= rental.start_date %></li>
      <li>End Date: <%= rental.end_date %></li>
      <p></p>
    <strong>Total Price: </strong><%= rental.book.daily_price * (rental.end_date.jd - rental.start_date.jd) %>
    <% end %>
  </ul>
<% end %>
<%= link_to "Back to browsing", root_path %>
<p></p>

app/views/rentals/new.html.erb
<%= simple_form_for [@book, @rental], data: { controller: 'flatpickr' } do |f| %>
  <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to browsing", root_path %>

app/views/rentals/show.html.erb
<h1> <%= @rental %></h1>
<p><%= link_to "Back to browsing books.", root_path %></p>
<p><%=  button_to "Delete", @rental, method: :delete %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "bab_logo.svg" %>
    <% end %>
    <h1 class="logo-type">Book a Book</h1>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <p class="hello">Hello <%= current_user.first_name.capitalize! %></p>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a book", new_book_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "istockphoto-1142665470-612x612.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My rentals", rentals_path, class:"btn btn-primary btn-lg" %>
              <%= link_to "My books", items_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/items.html.erb
<div class="content">
<h1> My Books </h1>
  <div class="container">
    <% current_user.books.each do |book| %>
      <div class="card">
        <%if book.cover.present?%>
          <%=  cl_image_tag(book.cover.key, :width => 250) %>
        <%else%>
          <%= cl_image_tag("v5hsn2kpxcxprmmx08o3nanwgb9w", :width => 250) %>
        <%end%>
        <p class="card-text"><%= book.title %></p>
        <p class="card-text"><%= book.daily_price %>€ %></p>
        <h6 class="card-text book-title"><em><%= book.description %></em></h6>
        <p><%= link_to "edit", edit_book_path(book), class: "btn btn-info btn-sm "%></p>
      </div>
    <% end %>
  </div>
</div>